//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenDbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potrawy
    {
        public Potrawy()
        {
            this.Skladniki1 = new HashSet<Skladniki>();
        }
    
        public int IdPotrawy { get; set; }
        public string NazwaPotrawy { get; set; }
        public string Skladniki { get; set; }
        public string Przygotowanie { get; set; }
    
        public virtual ICollection<Skladniki> Skladniki1 { get; set; }
    }
}
