//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenDbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladniki
    {
        public int IdSkladnik { get; set; }
        public Nullable<int> IdPotrawy { get; set; }
        public string Skladnik { get; set; }
    
        public virtual Potrawy Potrawy { get; set; }
    }
}
